apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: shop.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shop-frontend-service
                port:
                  number: 80
